import "./globals.css";
import { Metadata, Viewport } from "next";
import { generateViewport } from "next";
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata = {
  applicationName: "SKBerry",
  title: {
    default: "Be anyone you want",
    template: "SKBerry",
  },
  description: "Be anyone you want",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "SKBerry",
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport = {
  themeColor: "#FFFFFF",
  width: "device-width",
  height: "device-height",
  initialScale: 1.0,
  minimumScale: 1.0,
  maximumScale: 1.0,
  userScalable: "no",
  viewportFit: "cover",
  themeColor: "#000000",
  backgroundColor: "#ffffff",
  display: "standalone",
  orientation: "portrait-primary",
  preferRelatedApplications: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
